language: r
warnings_are_errors: true
sudo: required

matrix:
    allow_failures:
        -os: osx
    include:
        - os: linux
          r: release
          dist: trusty # 14.04
          env: R_CODECOV=true
          before_install:
              - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
              - sudo apt-get --yes --force-yes update -qq
              - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev libudunits2-dev
          #r_build_args: '--no-build-vignettes'
          #r_check_args: '--ignore-vignettes'
        - os: linux
          r: release
          dist: precise # 12.04
          before_install:
              - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
              - sudo apt-get --yes --force-yes update -qq
              - sudo apt-get install --yes libhdf5-serial-dev
              - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev libudunits2-dev
        - os: linux
          r: devel
          dist: trusty
          before_install:
              - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
              - sudo apt-get --yes --force-yes update -qq
              - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev libudunits2-dev
          r_build_args: '--no-build-vignettes'
          r_check_args: '--ignore-vignettes'
        - os: osx
          r: release
          # http://gis.stackexchange.com/questions/155403/installing-gdal-on-macosx
          #before_install:
          #    - brew tap osgeo/osgeo4mac
          brew_packages: gdal-20
          r_build_args: '--no-build-vignettes'
          r_check_args: '--ignore-vignettes'


notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
      - jimhester/covr

after_success:
      - Rscript -e 'covr::codecov()'
